export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div
          style={{
            minHeight: "100vh",
            border: "2px solid black",
            boxSizing: "border-box",
          }}
        >
          {children}
        </div>
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "4rem",
          }}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
