import { Metadata } from "next";
import "./global.css";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial",
    template: "%s | Next.js",
    absolute: "",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "4rem",
          }}
        >
          <p>This is Header</p>
        </header>
        <div
          style={{
            minHeight: "100vh",
            border: "2px solid black",
            boxSizing: "border-box",
          }}
        >
          {children}
        </div>
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "4rem",
          }}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
